---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-demo
  name: pipeline-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-demo
  template:
    metadata:
      labels:
        app: pipeline-demo
    spec:
      containers:
      - image: km20/devops:latest
        imagePullPolicy: Always
        name: pipeline-demo

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipeline-demo
  name: pipeline-demo
spec:
  type: NodePort
  selector:
    app: pipeline-demo
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      # nodePort: 30007